version: '3'

services:
  app:
    container_name: chat_node_app
    build:
      context: .
      dockerfile: ./${NODE_ENV}.Dockerfile
    env_file: ./env/.dev
    volumes:
      - ./src:/app/src
    # depends_on:
    #   - postgres
    ports:
      - '3000:3000'



#   postgres:
#     container_name: ChatPostgres
#     image: 10.3
#     restart: always
#     environment:
#       - POSTGRES_USER=sammy
#       - POSTGRES_PASSWORD=your_password
#     volumes:
#       - postgresql_data:/var/lib/postgresql/data
#     ports:
#       - '5432:5432'

# volumes:
#   postgresql_data: