version: '3'

services:
  app:
    container_name: chat_node_app
    build:
      context: ../
      dockerfile: ./docker/${NODE_ENV}.Dockerfile
    env_file: ../env/.dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'


    # depends_on:
    #   - postgres

#   postgres:
#     container_name: ChatPostgres
#     image: 10.3
#     restart: always
#     environment:
#       - POSTGRES_USER=sammy
#       - POSTGRES_PASSWORD=your_password
#     volumes:
#       - postgresql_data:/var/lib/postgresql/data
#     ports:
#       - '5432:5432'

# volumes:
#   postgresql_data: